# fly.toml file generated for harry-da on 2023-03-30T09:24:45-05:00

app = "harry-da"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"
processes = []

[build]
  image = "harryly/datingapp:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__CloudName = "dwbtlm8oe"
  CloudinarySettings__ApiKey = "257472849828813"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
