# fly.toml file generated for harry-dating-app on 2023-04-16T03:26:59-05:00

app = "harry-dating-app"
primary_region = "iad"

[build]
  image = "harryly140/datingapp:latest"
  
[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__CloudName = "ddqpvjrjr"
  CloudinarySettings__ApiKey = "871883379922617"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
